#!/usr/bin/env bash
set -eo pipefail

echo "Installing simplexup..."

BASE_DIR="${XDG_CONFIG_HOME:-$HOME}"
SIMPLEX_DIR="${SIMPLEX_DIR:-"$BASE_DIR/.simplex"}"
SIMPLEX_BIN_DIR="$SIMPLEX_DIR/bin"

BIN_URL="https://raw.githubusercontent.com/ikripaka/smplx/master/simplexup/simplexup"
BIN_PATH="$SIMPLEX_BIN_DIR/simplexup"

# Create the .simplex bin directory and simplexup binary if it doesn't exist.
mkdir -p "$SIMPLEX_BIN_DIR"
curl -sSf -L "$BIN_URL" -o "$BIN_PATH"
chmod +x "$BIN_PATH"

# Store the correct profile file (i.e. .profile for bash or .zshenv for ZSH).
case $SHELL in
*/zsh)
    PROFILE="${ZDOTDIR-"$HOME"}/.zshenv"
    PREF_SHELL=zsh
    ;;
*/bash)
    PROFILE=$HOME/.bashrc
    PREF_SHELL=bash
    ;;
*/fish)
    PROFILE=$HOME/.config/fish/config.fish
    PREF_SHELL=fish
    ;;
*)
    echo "simplexup: could not detect shell, manually add ${SIMPLEX_BIN_DIR} to your PATH."
    exit 1
esac

# Only add simplexup if it isn't already in PATH.
if [[ ":$PATH:" != *":${SIMPLEX_BIN_DIR}:"* ]]; then
    # Add the simplexup directory to the path and ensure the old PATH variables remain.
    if [[ "$PREF_SHELL" == "fish" ]]; then
        echo >> "$PROFILE" && echo "fish_add_path -a \"$SIMPLEX_BIN_DIR\"" >> "$PROFILE"
    else
        echo >> "$PROFILE" && echo "export PATH=\"\$PATH:$SIMPLEX_BIN_DIR\"" >> "$PROFILE"
    fi
fi

echo
echo "Detected your preferred shell is $PREF_SHELL and added simplexup to PATH."
echo
echo "Run 'source $PROFILE' or start a new terminal session to use simplexup."
echo
echo "Then, simply run 'simplexup' to install Simplex."
